CREATE OR REPLACE FUNCTION AVG_SAL RETURN EMPLOYEE.SALARY%TYPE AS
    AVG_SALARY DECIMAL(10, 2);
BEGIN
    SELECT
        AVG(SALARY) INTO AVG_SALARY
    FROM
        EMPLOYEE;
    RETURN AVG_SALARY;
END;
/

DECLARE
    AVG_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN
    AVG_SALARY := AVG_SAL();
    DBMS_OUTPUT.PUT_LINE('AVG Salary is '
                         || AVG_SALARY);
END;
/