CREATE OR REPLACE FUNCTION MAX_SAL RETURN EMPLOYEE.SALARY%TYPE AS
    MAX_SALARY DECIMAL(10, 2);
BEGIN
    SELECT
        MAX(SALARY) INTO MAX_SALARY
    FROM
        EMPLOYEE;
    RETURN MAX_SALARY;
END;
/

DECLARE
    MAX_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN
    MAX_SALARY := MAX_SAL();
    DBMS_OUTPUT.PUT_LINE('Max Salary is '
                         || MAX_SALARY);
END;
/