CREATE OR REPLACE PROCEDURE TOTAL_EMPLOYEES (
    EMPLOYEE_COUNT OUT INT
) AS
BEGIN
    SELECT
        COUNT(*) INTO EMPLOYEE_COUNT
    FROM
        EMPLOYEE;
END;
/

DECLARE
    EMP_COUNT         INT;
    NO_EMPLOYEE_FOUND EXCEPTION;
BEGIN
    TOTAL_EMPLOYEES(EMP_COUNT);
    IF EMP_COUNT = 0 THEN
        RAISE NO_EMPLOYEE_FOUND;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Total Employees: '
                             || EMP_COUNT);
    END IF;
EXCEPTION
    WHEN NO_EMPLOYEE_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No Employee Found');
END;
/