CREATE TABLE EMPDEL (
    ENO VARCHAR(10) PRIMARY KEY,
    ENAME VARCHAR(20),
    DEPARTMENT VARCHAR(20),
    SALARY DECIMAL(10, 2),
    DELETED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER ON_DELETE_EMP BEFORE
    DELETE ON EMP FOR EACH ROW
BEGIN
    INSERT INTO EMPDEL (
        ENO,
        ENAME,
        DEPARTMENT,
        SALARY
    ) VALUES (
        :OLD.ENO,
        :OLD.ENAME,
        :OLD.DEPARTMENT,
        :OLD.SALARY
    );
    DBMS_OUTPUT.PUT_LINE('Record Deleted');
END;
/

BEGIN
    DELETE FROM EMP
    WHERE
        ENO='E03';
END;
/

```