CREATE OR REPLACE TRIGGER SAL_DIFF BEFORE
    UPDATE ON EMP FOR EACH ROW
DECLARE
    V_SAL_DIFF NUMBER;
BEGIN
    V_SAL_DIFF :=:NEW.SALARY - :OLD.SALARY;
    DBMS_OUTPUT.PUT_LINE('SALARY DIFFERENCE IS '
                         || V_SAL_DIFF);
END;
/

BEGIN
    UPDATE EMP
    SET
        SALARY=100000
    WHERE
        ENO='E05';
END;
/