CREATE TABLE NEWEMP (
    EID VARCHAR(10) NOT NULL,
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER(10, 2)
);

CREATE OR REPLACE TRIGGER NEW_EMP BEFORE
    INSERT ON EMP FOR EACH ROW
BEGIN
    INSERT INTO NEWEMP VALUES(
        :NEW.ENO,
        :NEW.DEPARTMENT,
        :NEW.SALARY
    );
END;
/