CREATE OR REPLACE PACKAGE EMP_PACKAGE AS

    PROCEDURE ADD_EMP(
        NO EMPLOYEE.ENO%TYPE,
        NAME EMPLOYEE.ENAME%TYPE,
        DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE,
        SALARY EMPLOYEE.SALARY%TYPE
    );

    PROCEDURE DELETE_EMP(
        NO EMPLOYEE.ENO%TYPE
    );
END EMP_PACKAGE;
/

CREATE OR REPLACE PACKAGE BODY EMP_PACKAGE AS

    PROCEDURE ADD_EMP(
        NO EMPLOYEE.ENO%TYPE,
        NAME EMPLOYEE.ENAME%TYPE,
        DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE,
        SALARY EMPLOYEE.SALARY%TYPE
    ) IS
    BEGIN
        INSERT INTO EMPLOYEE VALUES(
            NO,
            NAME,
            DEPARTMENT,
            SALARY
        );
        DBMS_OUTPUT.PUT_LINE(NO
                             || ' Inserted');
    END ADD_EMP;

    PROCEDURE DELETE_EMP(
        NO EMPLOYEE.ENO%TYPE
    ) IS
    BEGIN
        DELETE FROM EMPLOYEE
        WHERE
            ENO = NO;
        DBMS_OUTPUT.PUT_LINE(NO
                             || ' Deleted');
    END DELETE_EMP;
END EMP_PACKAGE;
/

DECLARE
    NO         EMPLOYEE.ENO%TYPE := &ENO;
    NAME       EMPLOYEE.ENAME%TYPE := '&NAME';
    DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE := '&DEPARTMENT';
    SALARY     EMPLOYEE.SALARY%TYPE := &SALARY;
BEGIN
    EMP_PACKAGE.ADD_EMP(NO, NAME, DEPARTMENT, SALARY);
    EMP_PACKAGE.DELETE_EMP(NO);
END;
/