CREATE OR REPLACE PACKAGE EMP_SAL IS

    PROCEDURE UPDATE_SAL(
        ENO EMPLOYEE.ENO%TYPE
    );
END EMP_SAL;
/

CREATE OR REPLACE PACKAGE BODY EMP_SAL IS

    PROCEDURE UPDATE_SAL(
        ENO EMPLOYEE.ENO%TYPE
    ) IS
    BEGIN
        UPDATE EMPLOYEE
        SET
            SALARY = SALARY +1000
        WHERE
            ENO = ENO;
    END UPDATE_SAL;
END EMP_SAL;
/

DECLARE
    ENO EMPLOYEE.ENO%TYPE := &ENO;
BEGIN
    EMP_SAL.UPDATE_SAL(ENO);
END;
/