CREATE OR REPLACE PACKAGE EMP_PAC IS

    PROCEDURE ADD_EMP(
        NO EMPLOYEE.ENO%TYPE,
        NAME EMPLOYEE.ENAME%TYPE,
        DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE,
        SALARY EMPLOYEE.SALARY%TYPE
    );

    PROCEDURE GET_EMP(
        NO EMPLOYEE.ENO%TYPE,
        EMP OUT EMPLOYEE%ROWTYPE
    );
END EMP_PAC;
/

CREATE OR REPLACE PACKAGE BODY EMP_PAC IS

    PROCEDURE ADD_EMP(
        NO EMPLOYEE.ENO%TYPE,
        NAME EMPLOYEE.ENAME%TYPE,
        DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE,
        SALARY EMPLOYEE.SALARY%TYPE
    ) IS
    BEGIN
        INSERT INTO EMPLOYEE VALUES(
            NO,
            NAME,
            DEPARTMENT,
            SALARY
        );
        DBMS_OUTPUT.PUT_LINE(NO
                             || ' Inserted');
    END ADD_EMP;

    PROCEDURE GET_EMP(
        NO EMPLOYEE.ENO%TYPE,
        EMP OUT EMPLOYEE%ROWTYPE
    ) IS
    BEGIN
        SELECT
            * INTO EMP
        FROM
            EMPLOYEE
        WHERE
            ENO=NO;
    END GET_EMP;
END EMP_PAC;
/

DECLARE
    NO         EMPLOYEE.ENO%TYPE := &ENO;
    NAME       EMPLOYEE.ENAME%TYPE := '&NAME';
    DEPARTMENT EMPLOYEE.DEPARTMENT%TYPE :='&DEPARTMENT';
    SALARY     EMPLOYEE.SALARY%TYPE := &SALARY;
    EMP        EMPLOYEE%ROWTYPE;
BEGIN
    EMP_PAC.ADD_EMP(NO, NAME, DEPARTMENT, SALARY);
    EMP_PAC.GET_EMP(NO, EMP);
    DBMS_OUTPUT.PUT_LINE('Eno: '
                         || EMP.ENO);
END;
/