CREATE OR REPLACE PROCEDURE DELETE_EMPLOYEE AS
BEGIN
    DELETE FROM EMPLOYEE
    WHERE
        DEPARTMENT = 'Finance';
    DBMS_OUTPUT.PUT_LINE('Employee deleted successfully');
END DELETE_EMPLOYEE;
/

BEGIN
    DELETE_EMPLOYEE;
END;
/