CREATE OR REPLACE FUNCTION GETTOTALHEIGHT RETURN INT AS
    TOTALHEIGHT INT;
BEGIN
    SELECT
        SUM(HEIGHT) INTO TOTALHEIGHT
    FROM
        PERSON;
    RETURN TOTALHEIGHT;
END GETTOTALHEIGHT;
/

DECLARE
    HEIGHT INT;
BEGIN
    HEIGHT := GETTOTALHEIGHT();
    DBMS_OUTPUT.PUT_LINE('Total Height is: '
                         || HEIGHT);
END;
/