CREATE OR REPLACE FUNCTION GETAVGWEIGHT RETURN INT AS
    AVGWEIGHT INT;
BEGIN
    SELECT
        AVG(WEIGHT) INTO AVGWEIGHT
    FROM
        PERSON;
    RETURN AVGWEIGHT;
END GETAVGWEIGHT;
/

DECLARE
    WEIGHT INT;
BEGIN
    WEIGHT := GETAVGWEIGHT();
    DBMS_OUTPUT.PUT_LINE('Avg weight is: '
                         || WEIGHT);
END;
/