CREATE OR REPLACE TRIGGER PERSON_DELETE_LOG AFTER
    DELETE OR UPDATE ON PERSON FOR EACH ROW
BEGIN
    INSERT INTO P_LOG (
        PID
    ) VALUES(
        :OLD.PID
    );
    DBMS_OUTPUT.PUT_LINE('PID: '
                         || :OLD.PID);
END;
/

CREATE TABLE P_LOG(
    PID VARCHAR(10),
    DELETED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);